/** This file is autogenerated */

import { ModuleWithProviders }  from "@angular/core";
import { Routes, RouterModule } from "@angular/router";
import { Main } from "./Component/Main/Main/Main";
import { Home }  from './Component/Home/Home/Home';
import { UserLogin }  from './Component/User/Login/Login';

const appRoutes: Routes = [
	{
		path: "Home",
		component : Home
	},
	{
		path: "UserLogin",
		component : UserLogin
	},
	{
		path: "",
		redirectTo: "/Home",
		pathMatch: "full"
	}
];
export const routing: ModuleWithProviders = RouterModule.forRoot(appRoutes);
export const declarations = [Main, Home, UserLogin];
