<?php

namespace LIM\MoreSalle\Repository;

/**
 * ReservationRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRessourceRepository extends \Doctrine\ORM\EntityRepository
{
}
