<?php

namespace LIM\MoreSalle\Repository;

/**
 * RessourceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
