/** This file is autogenerated */

import { ModuleWithProviders }  from "@angular/core";
import { Routes, RouterModule } from "@angular/router";
import { Home } from "./Component/Home/Home/Home";
import { Main } from "./Component/Main/Main/Main";
import { UserLogin } from "./Component/User/Login/Login";
const appRoutes: Routes = [
	{
		path: "Home",
		component : Home
	},
	{
		path: "Main",
		component : Main
	},
	{
		path: "UserLogin",
		component : UserLogin
	},
	{
		path: "",
		redirectTo: "/Index",
		pathMatch: "full"
	}
];
export const routing: ModuleWithProviders = RouterModule.forRoot(appRoutes);
export const declarations = [Home,Main,UserLogin];
