<?php

namespace Emeric0101\PHPAngular\Repository;

/**
 * EntityTestPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityTestPRepository extends \Doctrine\ORM\EntityRepository
{
}
