<?php

namespace LIM\MoreSalle\Repository;

/**
 * EntrepotRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepotRessourceRepository extends \Doctrine\ORM\EntityRepository
{
}
